#!/bin/bash
mkdir $HOME/opt
cd $HOME/opt
git clone https://github.com/UG4/ughub

export UG4_ROOT=$HOME/opt/ug4

# UG4
mkdir $UG4_ROOT
cd $UG4_ROOT
../ughub/ughub init
../ughub/ughub install Examples
cd $HOME/opt/ug4
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DConvectionDiffusion=ON -DDIM="2;3" -DCPU=1 ..
make -j12

# Xeus kernel
cd $HOME/opt/
git clone https://github.com/UG4/xeus-ug4
mkdir xeus-ug4/build
cd xeus-ug4/build
# cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
make 
make install
