#!/bin/bash
cd $HOME
git clone https://github.com/UG4/ughub
mkdir $HOME/ug4
cd $HOME/ug4
../ughub/ughub init
../ughub/ughub install Examples
cd $HOME/ug4
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DConvectionDiffusion=ON ..
